/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyChooseUsRouteImport } from './routes/why-choose-us'
import { Route as TourRouteImport } from './routes/tour'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SavingsPlanRouteImport } from './routes/savings-plan'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as FirstVisitRouteImport } from './routes/first-visit'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WhyChooseUsRoute = WhyChooseUsRouteImport.update({
  id: '/why-choose-us',
  path: '/why-choose-us',
  getParentRoute: () => rootRouteImport,
} as any)
const TourRoute = TourRouteImport.update({
  id: '/tour',
  path: '/tour',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsPlanRoute = SavingsPlanRouteImport.update({
  id: '/savings-plan',
  path: '/savings-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstVisitRoute = FirstVisitRouteImport.update({
  id: '/first-visit',
  path: '/first-visit',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/first-visit': typeof FirstVisitRoute
  '/forms': typeof FormsRoute
  '/savings-plan': typeof SavingsPlanRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/testimonials': typeof TestimonialsRoute
  '/tour': typeof TourRoute
  '/why-choose-us': typeof WhyChooseUsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/first-visit': typeof FirstVisitRoute
  '/forms': typeof FormsRoute
  '/savings-plan': typeof SavingsPlanRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/testimonials': typeof TestimonialsRoute
  '/tour': typeof TourRoute
  '/why-choose-us': typeof WhyChooseUsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/first-visit': typeof FirstVisitRoute
  '/forms': typeof FormsRoute
  '/savings-plan': typeof SavingsPlanRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/testimonials': typeof TestimonialsRoute
  '/tour': typeof TourRoute
  '/why-choose-us': typeof WhyChooseUsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/community'
    | '/contact'
    | '/doctors'
    | '/first-visit'
    | '/forms'
    | '/savings-plan'
    | '/services'
    | '/team'
    | '/testimonials'
    | '/tour'
    | '/why-choose-us'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/community'
    | '/contact'
    | '/doctors'
    | '/first-visit'
    | '/forms'
    | '/savings-plan'
    | '/services'
    | '/team'
    | '/testimonials'
    | '/tour'
    | '/why-choose-us'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/community'
    | '/contact'
    | '/doctors'
    | '/first-visit'
    | '/forms'
    | '/savings-plan'
    | '/services'
    | '/team'
    | '/testimonials'
    | '/tour'
    | '/why-choose-us'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  DoctorsRoute: typeof DoctorsRoute
  FirstVisitRoute: typeof FirstVisitRoute
  FormsRoute: typeof FormsRoute
  SavingsPlanRoute: typeof SavingsPlanRoute
  ServicesRoute: typeof ServicesRoute
  TeamRoute: typeof TeamRoute
  TestimonialsRoute: typeof TestimonialsRoute
  TourRoute: typeof TourRoute
  WhyChooseUsRoute: typeof WhyChooseUsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-choose-us': {
      id: '/why-choose-us'
      path: '/why-choose-us'
      fullPath: '/why-choose-us'
      preLoaderRoute: typeof WhyChooseUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour': {
      id: '/tour'
      path: '/tour'
      fullPath: '/tour'
      preLoaderRoute: typeof TourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings-plan': {
      id: '/savings-plan'
      path: '/savings-plan'
      fullPath: '/savings-plan'
      preLoaderRoute: typeof SavingsPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-visit': {
      id: '/first-visit'
      path: '/first-visit'
      fullPath: '/first-visit'
      preLoaderRoute: typeof FirstVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  DoctorsRoute: DoctorsRoute,
  FirstVisitRoute: FirstVisitRoute,
  FormsRoute: FormsRoute,
  SavingsPlanRoute: SavingsPlanRoute,
  ServicesRoute: ServicesRoute,
  TeamRoute: TeamRoute,
  TestimonialsRoute: TestimonialsRoute,
  TourRoute: TourRoute,
  WhyChooseUsRoute: WhyChooseUsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
